a <- read.csv("~/household_power_consumption.txt", sep=";", na.strings="?");
b <- subset(a, Date == "1/2/2007");
c <- subset(a, Date == "2/2/2007");
d <- rbind(b,c);
row.names(d) <- NULL;
e <- strptime(paste(d$Date, d$Time),"%d/%m/%Y %H:%M:%S");
png("plot3.png");
plot(e, d$Sub_metering_1, col="Black", ylab="Energy sub metering", xlab = "",type="l");
lines(e, d$Sub_metering_2, col="Red");
lines(e, d$Sub_metering_3, col="Blue");
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"));
dev.off();
